build:
  maxIssues: 0
  excludeCorrectable: false
  weights: {}

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: ''

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude: []

naming:
  active: true

  # 일반 함수 규칙 (Composable 제외)
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*' # camelCase
    excludeClassPattern: '$^'
    excludes:
      - '**/*Composable.kt'
      - '**/*Screen.kt'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'

  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
    privateParameterPattern: '[a-z][A-Za-z0-9]*'

  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'

  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'

  MemberNameEqualsClassName:
    active: true
    ignoreOverridden: true

  TopLevelPropertyNaming:
    active: true
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    constantPattern: '[A-Z][_A-Z0-9]*'

  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
  TrailingWhitespace:
    active: true

empty-blocks:
  active: true
  EmptyFunctionBlock:
    active: true

exceptions:
  active: true
  PrintStackTrace:
    active: true
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - 'InterruptedException'
      - 'MalformedURLException'
      - 'NumberFormatException'
      - 'ParseException'
    allowedExceptionNameRegex: '_|(ignore|expected).*'